### ISSUE TITLE
How to get the posfiles of imputation_files

### ISSUE THREAD

**Issue by Gody1111** [scbaca/chip_imputation#2]
Hi, I am very interested in the approach to imputing genotypes from bam files of ChIPseq and ATACseq. Since I am a newbie, I have the following doubts:
1. imputation_files can be downloaded from https://mathgen.stats.ox.ac.uk/impute/1000GP_Phase3.html, but the posfiles are different from the files I downloaded. I'd like to know if any changes were made to the file.
2. Is there a corresponding standard just how to choose qc snps？
3. I am concerned that the author's article published in Nature Genetics focuses on European populations, how should I change the parameters if my samples originate from East Asian populations？
Thanks to the author for providing such a convenient and good method. I am looking forward to receiving the author's response to my question.

**Comment by scbaca** [comment]
Thanks for your interest! For non-European samples, it would be a good idea to use reference data from the appropriate population (e.g. East Asian). For our work in mostly European Ancestry samples, we used SNPs with mAF > 0.01 in this population, and you may want to apply a similar filter. The STITCH documentation may be helpful for more info on posfiles and how they are used: https://github.com/rwdavies/STITCH

**Comment by Gody1111** [comment]
Thank you for your reply, it helps me tremendously!



At 2023-09-09 00:26:39, "scbaca" ***@***.***> wrote:

Thanks for your interest! For non-European samples, it would be a good idea to use reference data from the appropriate population (e.g. East Asian). For our work in mostly European Ancestry samples, we used SNPs with mAF > 0.01 in this population, and you may want to apply a similar filter. The STITCH documentation may be helpful for more info on posfiles and how they are used: https://github.com/rwdavies/STITCH
